- name: install basic utils, shells, apps
  community.general.pacman:
   name:
    - base-devel
    - emacs-nox
    - chrony
    - chronie
    - git
    - sudo
    - yajl
    - wget 
   state: present


- name: Install download utils
  pacman:
    name:
      - curl
      - wget
    state: present
