
- name: sync-clock-at-boot
  become: true
  copy: 
   src: files/usr/local/sbin/sync-clock-at-boot
   dest: /usr/local/sbin/sync-clock-at-boot
   force: true
   owner: root
   group: root
   mode: u+rwx,g+r,o+r

- name: create export in root bashrc
  shell: echo "@reboot /usr/local/sbin/sync-clock-at-boot" >>/root/.bashrc
  become: true

- name: create export in root bashrc
  shell: echo "export EDITOR='emacs'" >>/root/.bashrc
  become: true
