
- name: sync-clock-at-boot
  become: true
  copy: 
   src: usr/local/sbin/sync-clock-at-boot
   dest: /usr/local/sbin/sync-clock-at-boot
   force: true
   owner: root
   group: root
   mode: u+rwx,g+r,o+r

- name: create export in root bashrc
  shell: echo "@reboot /usr/local/sbin/sync-clock-at-boot" >>/root/.bashrc
  become: true

- name: create export in root bashrc
  shell: echo "export EDITOR='emacs'" >>/root/.bashrc
  become: true

- name: create cd/etc in root bashrc
  shell: echo "cd /etc" >>/root/.bashrc
  become: true

- name: create git username 
  shell: git config --global user.name "root"
  become: true

- name: create git email 
  shell: git config --global user.email "root@RPI"
  become: true

- name: create git repo /etc
  shell: cd /etc && git init
  become: true

  #- name: create git commit 
  #  shell: cd /etc && pwd && git add /etc/pacman.conf /etc/makepkg.conf && git commit -m "add some files to repo"
  #  become: true

- name: set time and date
  shell: timedatectl set-timezone Europe/Amsterdam && timedatectl status
  become: true

  #- name: create git commit 
  #  shell: cd /etc && git add sudoers && git commit -m "orig sudoers file"
  #  become: true

  #- name: allow sudo | uncomment wheel
  #  become: true
  #  replace:
  #    path: /etc/sudoers
  #    regexp: '{{ item.regexp }}'
  #    replace: '{{ item.replace }}'
  #  with_items:
  #    - { regexp: '^# wheel ALL=(ALL) ALL$', replace: '%wheel ALL=(ALL) ALL' }
  #
  #- name: create git commit 
  #  shell: cd /etc && git add sudoers && git commit -m "modified sudoers file"
  #  become: true

- name:  export man and ls colours
  shell: cat etc/bash.bashrc >> /etc/bash.bashrc
  become: true
- name: create git commit 
  shell: cd /etc && git add bash.bashrc && git commit -m "modified bashrc in /etc"
  become: true


- name:  export root prompt
  shell: echo 'export PS1="[\[\033[1;41m\]\u\[\033[0;1;7m\]@\[\033[0;1;44m\]\h\[\033[0m\] \W]# "'>> /root/.bashrc
  become: true

- name: export prompt
  shell: echo 'export PS1="[\[\033[1;31m\]\u\[\033[0m\]@\[\033[1;34m\]\h\[\033[0m\] \W]\$ "'>> /home/opsstudent/.bashrc
  become: true

